WebTimeSheetManagement-master/WebTimeSheetManagement/Controllers/TimeSheetMasterExportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Helpers;
using WebTimeSheetManagement.Interface;
using WebTimeSheetManagement.Models;

namespace WebTimeSheetManagement.Controllers
{
    [ValidateSuperAdminSession]
    public class TimeSheetMasterExportController : Controller
    {
        ITimeSheetExport _ITimeSheetExport;
        ITimeSheet _ITimeSheet;
        public TimeSheetMasterExportController()
        {
            _ITimeSheetExport = new TimeSheetExportConcrete();
            _ITimeSheet = new TimeSheetConcrete();
        }

        [HttpGet]
        public ActionResult Report()
        {
            return View(new TimeSheetExportUserModel());
        }

        [HttpPost]
        public ActionResult Report(TimeSheetExportUserModel objtimesheet)
        {
            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            try
            {

                dt.Columns.Add("ProjectName", typeof(string));
                dt.Columns.Add("Sunday", typeof(string));
                dt.Columns.Add("Monday", typeof(string));
                dt.Columns.Add("Tuesday", typeof(string));
                dt.Columns.Add("Wednesday", typeof(string));
                dt.Columns.Add("Thursday", typeof(string));
                dt.Columns.Add("Friday", typeof(string));
                dt.Columns.Add("Saturday", typeof(string));
                dt.Columns.Add("Total", typeof(string));
                dt.Columns.Add("Description", typeof(string));

                var filename = "TimesheetMaster";

                var timesheetdata = _ITimeSheetExport.GetTimeSheetMasterIDTimeSheet(objtimesheet.FromDate, objtimesheet.ToDate);

                if (timesheetdata != null)
                {
                    if (timesheetdata.Tables.Count > 0)
                    {
                        if (timesheetdata.Tables[0].Rows.Count == 0)
                        {
                            TempData["NoExportMessage"] = "No Data to Export";
                            return View("TimeSheetReport", new TimeSheetExportUserModel());
                        }
                        else
                        {


                            for (int k = 0; k < timesheetdata.Tables[0].Rows.Count; k++)
                            {
                                var timesheetID = Convert.ToInt32(timesheetdata.Tables[0].Rows[k]["TimeSheetMasterID"]);

                                var data = _ITimeSheet.GetPeriodsbyTimeSheetMasterID(Convert.ToInt32(timesheetID));

                                DataRow row2 = dt.NewRow();
                                row2["ProjectName"] = "";
                                row2["Sunday"] = "";
                                row2["Monday"] = "";
                                row2["Tuesday"] = "";
                                row2["Wednesday"] = "";
                                row2["Thursday"] = "";
                                row2["Friday"] = "";
                                row2["Saturday"] = "";
                                row2["Total"] = "";
                                row2["Description"] = "";
                                dt.Rows.Add(row2);

                                DataRow row = dt.NewRow();
                                row["ProjectName"] = "";
                                row["Sunday"] = data[0].Period;
                                row["Monday"] = data[1].Period;
                                row["Tuesday"] = data[2].Period;
                                row["Wednesday"] = data[3].Period;
                                row["Thursday"] = data[4].Period;
                                row["Friday"] = data[5].Period;
                                row["Saturday"] = data[6].Period;
                                row["Total"] = "";
                                row["Description"] = "";
                                dt.Rows.Add(row);

                                var ListofProjectNames = _ITimeSheet.GetProjectNamesbyTimeSheetMasterID(Convert.ToInt32(timesheetID));

                                for (int i = 0; i < ListofProjectNames.Count(); i++)
                                {
                                    var ListofHours = MethodonViews.GetHoursbyTimeSheetMasterID(timesheetID, ListofProjectNames[i].ProjectID);
                                    var ListofDescription = WebTimeSheetManagement.Helpers.MethodonViews.GetDescriptionbyTimeSheetMasterID(timesheetID, ListofProjectNames[i].ProjectID);
                                    DataRow row1 = dt.NewRow();
                                    row1["ProjectName"] = ListofProjectNames[i].ProjectName;
                                    row1["Sunday"] = ListofHours[0].Hours;
                                    row1["Monday"] = ListofHours[1].Hours;
                                    row1["Tuesday"] = ListofHours[2].Hours;
                                    row1["Wednesday"] = ListofHours[3].Hours;
                                    row1["Thursday"] = ListofHours[4].Hours;
                                    row1["Friday"] = ListofHours[5].Hours;
                                    row1["Saturday"] = ListofHours[6].Hours;
                                    row1["Total"] = ListofHours[7].Hours;
                                    row1["Description"] = Convert.ToString(ListofDescription);
                                    dt.Rows.Add(row1);
                                }
                            }
                            ds.Tables.Add(dt);
                            var gv = new GridView();
                            gv.DataSource = ds;
                            gv.DataBind();
                            Response.ClearContent();
                            Response.Buffer = true;
                            Response.AddHeader("content-disposition", "attachment; filename=" + filename.Trim() + ".xls" + "");
                            Response.ContentType = "application/ms-excel";
                            Response.Charset = "";
                            StringWriter objStringWriter = new StringWriter();
                            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                            gv.RenderControl(objHtmlTextWriter);
                            Response.Output.Write(objStringWriter.ToString());
                            Response.Flush();
                            Response.End();
                        }
                    }
                }
                return View("Report", new TimeSheetExportUserModel());
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                ds.Dispose();
            }
        }


    }
}

WebTimeSheetManagement-master/WebTimeSheetManagement/Views/TimeSheetMasterExport/Report.cshtml
@model WebTimeSheetManagement.Models.TimeSheetExportUserModel
@{
    ViewBag.Title = "TimeSheetReport";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<script>
    if ('@TempData["NoExportMessage"]' != '') {
        alert('@TempData["NoExportMessage"]');
    }
</script>

@using (Html.BeginForm("Report", "TimeSheetMasterExport", FormMethod.Post))
{
    <div style="margin-top:10px;"></div>
    <div class="panel panel-default">
        <div class="panel-heading">TimeSheet Report</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.FromDate, new { @class = "manadatory" })
                    @Html.TextBoxFor(model => model.FromDate, new { @class = "form-control", @onkeypress = "return false;" })
                    @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.ToDate, new { @class = "manadatory" })
                    @Html.TextBoxFor(model => model.ToDate, new { @class = "form-control", @onkeypress = "return false;" })
                    @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                </div>
            </div>
            <div style="margin-top:10px;"></div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-offset-0 col-md-12">
                        <input type="submit" value="Export to Excel" class="btn btn-info" />
                    </div>
                </div>
            </div>
        </div>
    </div>

}

<script type="text/javascript">

    $(document).ready(function () {
        $('#ToDate').prop('disabled', true);
        $("#FromDate").datepicker
            ({
                dateFormat: "yy-mm-dd",
                changeMonth: true,
                numberOfMonths: 1,
                changeYear: true,
                yearRange: new Date().getFullYear() + ':' + new Date().getFullYear(),
                onSelect: function (date) {

                    $('#ToDate').prop('disabled', false);
                    var dt2 = $('#ToDate');
                    var startDate = $(this).datepicker('getDate');
                    var minDate = $(this).datepicker('getDate');
                    dt2.datepicker('setDate', minDate);
                    startDate.setDate(startDate.getDate() + 60);
                    //sets dt2 maxDate to the last day of 30 days window
                    dt2.datepicker('option', 'maxDate', startDate);
                    dt2.datepicker('option', 'minDate', minDate);
                    $(this).datepicker('option', 'minDate', minDate);

                }
            });
    });
    $(document).ready(function () {
        $("#ToDate").datepicker
            ({
                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                numberOfMonths: 1,
                yearRange: new Date().getFullYear() + ':' + new Date().getFullYear(),
                onSelect: function (date) {

                }
            });
    });
</script>